<div class="vivian-cards-set">
		<!-- <a class="card card-1" href="javascript:void(0)"></a>
		<a class="card card-2" href="javascript:void(0)"></a>
		<a class="card card-3" href="javascript:void(0)"></a>
		<a class="card card-4" href="javascript:void(0)"></a>
		<a class="card card-5" href="javascript:void(0)"></a>
		<a class="card card-6" href="javascript:void(0)"></a>
		 -->
		 <p><?php echo $this->__("<a target='_blank' title='see return&exchange in a new window' href='%s' style='text-decoration:underline;'>Returns&Exchange policy of catwalk88</a>",$this->getUrl('return-exchange')) ?></p>
		 <img alt="" src="<?php echo Mage::getBaseUrl('media').'/wysiwyg/banner_image/_5.27-05.jpg'?>" >
</div>
