<div class="box J_TBox clearfix">
<div class="ym9_tablist">
<div class="mhd trelative autohd"><?php
echo $this->getLayout()->getBlock('static_block_banner_1')->toHtml();
?></div>
<div class="mbd"><?php
echo $this->getLayout()->getBlock('static_block_product_list_1')->toHtml();
?></div>
</div>
</div>
<div class="box J_TBox clearfix">
<div class="ym9_tablist">
<div class="mbd">
<?php 
	echo $this->getLayout()->getBlock('static_block_product_list_2')->toHtml();
?>
</div>
</div>
</div>
<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border">
		<div class="bd">
			<div class="custom-area">
				<?php 
					echo $this->getLayout()->getBlock('static_block_banner_2')->toHtml();
				?>
				<?php 
					echo $this->getLayout()->getBlock('static_block_product_list_3')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>
<div class="box J_TBox tran_box">
	<div class="ym9_l_product">
		<div class="mhd trelative autohd">
			<?php 
				echo $this->getLayout()->getBlock('static_block_banner_3')->toHtml();
			?>
		</div>
		<div class="mbd mbd_n">
			<div class="tgrid xsjabs">
			<?php 
				echo $this->getLayout()->getBlock('static_block_product_list_4')->toHtml();
			?>
			</div>
		</div>
	</div>
</div>


<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border ">
		<div class="bd">
			<div class="custom-area">
				<?php 
					echo $this->getLayout()->getBlock('static_block_banner_4')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>

<div class="box J_TBox">
	<div class="ym9_collist">
		<div class="mbd mbd_n">
			<?php 
				echo $this->getLayout()->getBlock('static_block_product_list_5')->toHtml();
			?>
		</div>
	</div>
</div>


<div class="box J_TBox tran_box">
	<div class="ym9_l_product">
		<div class="mhd trelative autohd">
			<?php 
				echo $this->getLayout()->getBlock('static_block_banner_5')->toHtml();
			?>
		</div>
		<div class="mbd mbd_n">
			<div class="tgrid xsjabs">
				<?php 
					echo $this->getLayout()->getBlock('static_block_product_list_6')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>

<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border ">
		<div class="bd">
			<div class="custom-area">
				<?php
					echo $this->getLayout()->getBlock('static_block_banner_6')->toHtml(); 
				?>
			</div>
		</div>
	</div>
</div>

<div class="box  J_TBox">
	<div class="ym7_a_class">
		<div class="mbd">
			<?php 
				echo $this->getLayout()->getBlock('static_block_category_list_1')->toHtml();
			?>
		</div>
	</div>
</div>

<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border ">
		<div class="bd">
			<div class="custom-area">
				<?php 
					echo $this->getLayout()->getBlock('static_block_product_list_7')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>


<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border ">
		<div class="bd">
			<div class="custom-area">
				<?php 
					echo $this->getLayout()->getBlock('static_block_product_list_8')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>

<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border ">
		<div class="bd">
			<div class="custom-area">
				<?php 
					echo $this->getLayout()->getBlock('static_block_product_list_9')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>

<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border ">
		<div class="bd">
			<div class="custom-area">
				<?php 
					echo $this->getLayout()->getBlock('static_block_product_list_10')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>


<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border ">
		<div class="bd">
			<div class="custom-area">
				<?php 
					echo $this->getLayout()->getBlock('static_block_product_list_11')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>


<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border ">
		<div class="bd">
			<div class="custom-area">
				<?php 
					echo $this->getLayout()->getBlock('static_block_banner_7')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>

<div class="box popf J_TBox tran_box">
	<div class="ym9_f_product">
		<div class="mbd mbd_n">
			<div class="tgrid xsjabs">
				<?php 
					echo $this->getLayout()->getBlock('static_block_product_list_12')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>

<div class="box J_TBox tshop-pbsm tshop-pbsm-ssd10c">
	<div class="shop-custom   no-border ">
		<div class="bd">
			<div class="custom-area">
				<?php 
					echo $this->getLayout()->getBlock('static_block_banner_8')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>


<div class="box popf J_TBox tran_box">
	<div class="ym9_f_product">
		<div class="mbd mbd_n">
			<div class="tgrid xsjabs">
				<?php 
					echo $this->getLayout()->getBlock('static_block_product_list_13')->toHtml();
				?>
			</div>
		</div>
	</div>
</div>

<div class="J_TBox">
	<div class="yf_a_footer">
		<?php 
		echo $this->getLayout()->getBlock('static_block_content_footer')->toHtml();
		?>
	</div>
</div>
<script type="text/javascript">
	(function($){
			$('.tb-shop .ym9_l_product a.xspicbg').each(function(){
				$(this).find('img:eq(0)').addClass('zimg');
				$(this).find('img:eq(1)').addClass('fimg');
			});
		
	})(jQuery);
</script>